name: Run Tests

on:
  push:
    branches:
      - main  # Vous pouvez spécifier la branche sur laquelle le workflow doit être exécuté
  pull_request:
    branches:
      - main  # Vous pouvez exécuter les tests lorsque vous ouvrez un pull request sur la branche principale
  # Vous pouvez aussi configurer un calendrier pour exécuter des tests régulièrement
  # schedule:
  #   - cron: '0 0 * * *'  # Exécuter tous les jours à minuit UTC

jobs:
  test:
    runs-on: ubuntu-latest  # Utilise l'environnement Ubuntu sur GitHub Actions

    steps:
      # Étape 1: Vérifier le code source du dépôt
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2: Installer Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Vous pouvez choisir la version de Python que vous souhaitez

      # Étape 3: Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assurez-vous que vos dépendances sont listées dans ce fichier

      # Étape 4: Exécuter les tests
      - name: Run tests
        run: |
          # Exécuter vos tests avec pytest ou unittest
          pytest tests  # Si vous utilisez unittest, vous pouvez remplacer cette ligne par 'python -m unittest discover'
